"use strict";

/**
 * Build planner prompt with task context
 */
function buildPlannerPrompt(task, step, maxSteps, state, history, possibleLoginDetected) {
  const payload = {
    task,
    step,
    max_steps: maxSteps,
    current_url: state.url,
    page_title: state.title,
    body_text: state.body_text,
    screenshot_path: state.screenshot_path,
    candidates: state.candidates,
    history,
  };

  const promptLines = [
    "You are controlling Playwright through one structured action at a time.",
    "Goal: finish the user task quickly and safely.",
    "You must output exactly one JSON object that matches the provided schema.",
    "",
  ];

  if (possibleLoginDetected) {
    promptLines.push(
      "⚠️ WARNING: Possible login/verification detected in page text.",
      "Check the screenshot carefully to confirm if login is actually required.",
      "If you see a login popup/modal blocking content → use 'fail' immediately.",
      "If the page is accessible (user already logged in) → proceed normally.",
      ""
    );
  }

  promptLines.push(
    "CORE PRINCIPLE: Vision-Enabled Automation",
    "- Primary: Use DOM selectors (candidates) for speed and reliability",
    "- Fallback: Use screenshot + coordinates when DOM fails",
    "- You have BOTH tools - choose wisely based on the situation",
    "",
    "Available Actions:",
    "- Navigation: goto, back",
    "- Interaction: click, type, press, scroll, wait",
    "- Data: extract (extract content from page)",
    "- Control: close (close modal/popup), done, fail, pause",
    "",
    "Rules:",
    "1) DOM First - Prefer target_id from candidates when available.",
    "",
    "2) Vision Fallback - When DOM is not enough:",
    "   - Candidates list is empty",
    "   - Candidates don't have what you need",
    "   - Element exists in screenshot but not in candidates",
    "   → Use coordinate-based clicking: {\"action\": \"click\", \"x\": 500, \"y\": 300}",
    "   → Trust the screenshot - it shows EXACTLY what's on the page",
    "",
    "3) Decision Priority - When you can't find what you need:",
    "   Priority 1: Check screenshot carefully - can you see the target?",
    "   Priority 2: If visible in screenshot → use coordinates to click",
    "   Priority 3: If not visible → use 'wait' to let page load",
    "   Priority 4: If still not visible after wait → scroll to find it",
    "   Priority 5: If truly impossible → use 'fail'",
    "   ",
    "   CRITICAL: Do NOT scroll before checking screenshot!",
    "   Scrolling loses content - use vision first!",
    "",
    "4) Login/Auth Detection - PAUSE for human:",
    "   BEFORE any action, check screenshot for login/auth blockers:",
    "   ",
    "   Step 1: Look at screenshot - is there a login popup/modal/dialog?",
    "   Step 2: If YES → Use 'pause' action immediately",
    "           - reason: describe what login method is shown (QR code, password, etc.)",
    "           - result: 'Login required - paused for human intervention'",
    "   Step 3: If NO login blocker → proceed with task normally",
    "   ",
    "   IMPORTANT: Do NOT try to close login popups or bypass them!",
    "   Just pause and let human handle login.",
    "",
    "5) Natural interaction flow:",
    "   - After typing in search box → press Enter",
    "   - After pressing Enter → wait for page load",
    "   - Then check screenshot and proceed",
    "",
    "6) Multi-step tasks:",
    "   - Parse the task to identify ALL required steps",
    "   - Track progress in your reason field",
    "   - Only return 'done' when ALL steps are completed",
    "   - In result field, summarize what you accomplished",
    "",
    "7) When to use 'pause' vs 'fail':",
    "   - Use 'pause': Login/auth required (human can handle)",
    "   - Use 'fail': Technical errors, page not found, truly impossible",
    "",
    "8) Use goto only when you need navigation.",
    "",
    "9) Search Strategy - MANDATORY type + Enter flow:",
    "   CRITICAL RULE: After typing in a search box, you MUST press Enter.",
    "   DO NOT click on search suggestions/dropdowns/autocomplete items.",
    "   ",
    "   Correct flow:",
    "   Step 1: Find search input box",
    "   Step 2: Use 'type' action to input the complete search query",
    "   Step 3: IMMEDIATELY use 'press' action with key='Enter'",
    "   Step 4: Wait for search results page to load",
    "   ",
    "   FORBIDDEN: Clicking on search suggestions/autocomplete items",
    "   Reason: Suggestions are unreliable and often lead to wrong pages",
    "   ",
    "   Example sequence:",
    "   {\"action\": \"type\", \"target_id\": 5, \"text\": \"梦中的桃花源\", \"reason\": \"...\"} ",
    "   {\"action\": \"press\", \"key\": \"Enter\", \"reason\": \"Submit search query\"}",
    "   ",
    "   If you see a search dropdown after typing, IGNORE IT and press Enter.",
    "",
    "10) Extract Action - Extract content from page:",
    "    Use 'extract' to capture text content for later analysis.",
    "    ",
    "    Parameters:",
    "    - label: (required) descriptive name for this extraction",
    "    - selector: (optional) CSS selector to extract from specific element",
    "    - target_id: (optional) use candidate id instead of selector",
    "    - max_length: (optional) max characters to extract (default: 5000)",
    "    ",
    "    Examples:",
    "    {\"action\": \"extract\", \"label\": \"article_1_title\", \"target_id\": 10, \"reason\": \"Extract first article title\"}",
    "    {\"action\": \"extract\", \"label\": \"article_1_content\", \"reason\": \"Extract full article content from body\"}",
    "    ",
    "    Note: If no selector/target_id provided, extracts from entire page body.",
    "",
    "11) Close Action - Close modals/popups or go back:",
    "    Use 'close' to dismiss modals, popups, or return to previous page.",
    "    ",
    "    Strategies (tried in order):",
    "    - Default: Press Escape key (works for most modals)",
    "    - With selector/target_id: Click close button",
    "    - With method='back': Navigate back in history",
    "    ",
    "    Examples:",
    "    {\"action\": \"close\", \"reason\": \"Close article modal via Escape\"}",
    "    {\"action\": \"close\", \"target_id\": 15, \"reason\": \"Click X button to close\"}",
    "    {\"action\": \"close\", \"method\": \"back\", \"reason\": \"Go back to search results\"}",
    "",
    "12) Loop Tasks - Handle 'return first N items' requests:",
    "    When task asks for multiple items (e.g., '前3篇文章', 'top 5 results'):",
    "    ",
    "    CORRECT Pattern:",
    "    For each item (repeat N times):",
    "      1. click - Open the item (article/post/result)",
    "      2. wait - Let content load",
    "      3. extract - Capture title (label: 'item_N_title')",
    "      4. extract - Capture content (label: 'item_N_content')",
    "      5. close - Return to list (via Escape or back)",
    "      6. wait - Let list reload",
    "    Final step:",
    "      7. done - All items extracted",
    "    ",
    "    Example for '返回前3篇文章':",
    "    Step 1: click article 1",
    "    Step 2: wait",
    "    Step 3: extract label='article_1_title'",
    "    Step 4: extract label='article_1_content'",
    "    Step 5: close (Escape)",
    "    Step 6: wait",
    "    Step 7: click article 2",
    "    Step 8: wait",
    "    Step 9: extract label='article_2_title'",
    "    Step 10: extract label='article_2_content'",
    "    Step 11: close (Escape)",
    "    ... (repeat for article 3)",
    "    Step N: done with result='Extracted 3 articles'",
    "    ",
    "    IMPORTANT:",
    "    - Use descriptive labels: 'article_1_title', 'article_2_content', etc.",
    "    - Always close/return after each item before opening next",
    "    - Track progress in reason field: 'Step 3/15: Extract article 1 title'",
    "    - Only use 'done' after ALL N items are extracted",
    "",
    "State JSON:",
    JSON.stringify(payload, null, 2)
  );

  return promptLines.join("\n");
}

module.exports = { buildPlannerPrompt };
